<?php 
    session_start();

    if( !isset($_SESSION["login"]) || $_SESSION["login"] == "admin" ) {
        header("Location: index.php");
        exit;
    }

?>

<!DOCTYPE html>
<html lang="en">
<head>

  <title>User Favorite</title>
  <link rel="stylesheet" href="headerFooter_user.css">
  <style>
    

    body {
      padding: 0px;
      margin: 0;
      background-color: rgb(213, 217, 226);
      position: relative;
      padding-top: 150px;
    }



      /* MAIN SECTION  */

      .main {
        position: relative;
        margin: 20px 0 40px 150px;
        padding: 0 0 50px 0;
        width: 85%;
        /* height: 850px; */
        background-color:  rgb(235, 238, 245) ;
        border-radius: 10px;
        border: #fff 1px solid;
        /* border: 2px solid #13836c; */
        overflow: hidden;
        box-shadow: 10px 5px 14px -4px rgba(0,0,0,0.5);
        -webkit-box-shadow: 10px 5px 14px -4px rgba(0,0,0,0.5);
        -moz-box-shadow: 10px 5px 14px -4px rgba(0,0,0,0.5);
        display: grid; 
        grid-template-columns: 1fr; 
        grid-template-rows: 0.3fr 1.7fr; 
        gap: 0px 0px; 
        grid-template-areas: 
          "headerMain"
          "cardGrid"; 

      }


      .headerMain {
        grid-area: headerMain; 
        background-image: linear-gradient( 76.3deg,  rgba(44,62,78,1) 12.6%, rgba(69,103,131,1) 82.8% );
      }
      .headerMain h6 {
        color: #fff;
        margin : 20px 0 10px 50px;
        font-family: verdana;
        font-size: 20px;
      }
      .headerMain p {
        color: #fff;
        font-family: verdana;
        margin : 10px 0 10px 50px;
      }


      .cardGrid {
        width: 100%;
        height: 100%;
        padding: 50px 20px 0 30px;
        /* background-color: #16a085; */
        grid-area: cardGrid;
        display: grid;
        grid-template-columns: repeat(4,1fr);

      }
      .cardGrid a {
        text-decoration: none;
        font-family: verdana;
      }
      .cardBox {
        width: 260px;
        height: 250px;
        border-radius: 10px;
        border:rgba(44,62,78,1) 2px solid ;
        /* background-color: #13836c; */
        grid-column-gap: 10px ;
        grid-row-gap: 1px ;
        overflow: hidden;
        box-shadow: 10px 5px 14px -4px rgba(0,0,0,0.5);
        -webkit-box-shadow: 10px 5px 14px -4px rgba(0,0,0,0.5);
        -moz-box-shadow: 10px 5px 14px -4px rgba(0,0,0,0.5);
        
      }
      .cardLink {
        margin-top: 66%;
        width: 100%;
        height: 80px;
        background-image: linear-gradient( 76.3deg,  rgba(44,62,78,1) 12.6%, rgba(69,103,131,1) 82.8% );
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding: 5px 0;
      }
      .cardLink span {
        font-size: 25px;
        color: #fff;
      }
      .cardLink p {
        color: #fff;
      }


  </style>
</head>
<body>
      <!-- header section starts  -->

    <header class="header">

        <a href="../beranda.php" class="logo"> <img src="../logo/resepIn.png" height="50px"></a>

        <nav class="navbar">
            <a href="../beranda.php">Beranda</a>
            <a href="../list.php">List</a>
            <a href="../news.php">News</a>
            <a href="../developer.php">Developer</a>
            <ion-icon class="iconProfile" name="person-circle-outline"></ion-icon>
        </nav>
        <!-- <div class="iconProfile">
        </div> -->
    </header>
    
    <!-- header section ends -->

  <header class="banner" id="mainHeader" role="banner">

    <nav role="navigation">
        <div class="top-header">
            <div class="navBurger">
                <div class="burger"></div>
            </div>
            
        </div>

<!-- This part is the navigation generated by Wordpress.  -->
        <ul id="menu-vertical-menu" class="nav">
            <li><a href="dashboardUser.php">Dashboard</a></li>
            <li><a href="dashboardUserProfile.php">Profile</a></li>
            <li><a href="dashboardUserFav.php">Favourite</a></li>
            <li><a href="dashboardUserOrder.php">Order</a></li>
            <li><a href="dashboardUserAccount.php">Account</a></li>
            <li><a href="#">Logout</a></li>
		</ul>
    </nav>
  </header>

  <section class="main">
    <div class="headerMain">
      <h6>Favourite</h6>
      <p>Kelola daftar favourite anda disini</p>
    </div>
    <div class="cardGrid">
      <a href="">
        <div class="cardBox">
          <div class="cardLink">
            <span>Nama Makanan</span>
            <p>Jenis makanan</p>
          </div>
        </div>
      </a>
      <a href="">
        <div class="cardBox">
          <div class="cardLink">
            <span>Nama Makanan</span>
            <p>Jenis makanan</p>
          </div>
        </div>
      </a>
      <a href="">
        <div class="cardBox">
          <div class="cardLink">
            <span>Nama Makanan</span>
            <p>Jenis makanan</p>
          </div>
        </div>
      </a>
      <a href="">
        <div class="cardBox">
          <div class="cardLink">
            <span>Nama Makanan</span>
            <p>Jenis makanan</p>
          </div>
        </div>
      </a>
      <a href="">
        <div class="cardBox">
          <div class="cardLink">
            <span>Nama Makanan</span>
            <p>Jenis makanan</p>
          </div>
        </div>
      </a>

        </div>
      </div>
    </div>
  </section>












      <!-- footer section starts  -->

  <!-- Site footer -->
  <footer class="site-footer">
            <!-- <img src="footerBG.jpg" alt=""> -->
            <div class="footerGrid">
                <div class="footerAbout">
                    <h6>About</h6>
                    <img src="../logo/resepIn.png" alt="">
                    <p>
                        ResepIn adalah platform tentang informasi resep dan
                        pemesanan makanan paling mudah dan efisien.
                    </p>
                </div>
                <div class="footerCategory">
                    <h6>Categories</h6>
                    <p>Recipe</p>
                    <p>Order</p>
                    <p>Food</p>
                    <p>Desktop</p>
                    <p>Information</p>
                </div>
                <div class="footerLink">
                    <h6>Quick Link</h6>
                    <a href="../about_us.php"><p>About Us</p></a>
                    <a href="../contact_us.php"><p>Contact Us</p></a>
                    <a href="../chef.php"><p>Chef</p></a>
                    <a href="../blog.php"><p>Blog</p></a>
                    <a href="../faq.php"><p>FAQs</p></a>
                    <a href="../review.php"><p>Review</p></a>
                    <a href="../shipping_and_processing.php"><p>Shipping and Processing</p></a>
                    <a href="../privacy_and_policy.php"><p>Privacy and Policy</p></a>
                    <a href="../terms_of_use.php"><p>Terms of Use</p></a>
                    <a href="../disclaimer.php"><p>Disclaimer</p></a>
                </div>
            </div>
            <hr />
            <div class="copyrightLogo">
                <p class="copyright-text">
                    Copyright &copy; 2023 All Rights Reserved by
                    <a href="#">Kelompok 4</a>
                </p>
                <div class="iconLogoFooter">
                    <a href="#"><ion-icon name="logo-facebook"></ion-icon></a>
                    <a href="#"><ion-icon name="logo-twitter"></ion-icon></a>
                    <a href="#"><ion-icon name="logo-instagram"></ion-icon></a>
                </div>
            </div>
        </footer>

    <!-- footer section ends -->

  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>